---
- name: Backup current host file
  copy: 
    src: /etc/ansible/hosts
    dest: ./original.hosts.backup
    
- name: Copy OpenShift hosts config
  template: src=ocphostconfig.j2 dest=/etc/ansible/hosts

- name: refresh
  meta: refresh_inventory

        




